// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgoeyvphuknbkaggcple.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnb2V5dnBodWtuYmthZ2djcGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODE5ODUsImV4cCI6MjA2NjI1Nzk4NX0.v0j8QX0uXBnfcGVhteRDxUFbXpaMaJMrrCH93htfpcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);